### ISSUE TITLE
Codefactor/pylint import issue

### ISSUE THREAD

**Issue by toonarmycaptain** [codefactor-io/codefactor#1]
I have a structure:
```
myproject/
    app_main.py
    my_app_files/
        some_script.py
```
`app_main` calls a `some_functon` from `some_script` via from `my_app_files.some_script  #import some_function` - which seems to be how PEP8 suggests. 
Yet Codacy seems to want met to reform it to `from _master.my_app_files.some_script import some_function` - which not only doesn't work, it doesn't make a lot of sense, since `_master` doesn't appear anywhere in my project. 

https://github.com/toonarmycaptain/dionysus/issues/5

**Comment by toonarmycaptain** [comment]
Curiously, this issue disappeared with another commit which didn't obviously impact or modify that line of code...

**Comment by cordis-dev** [comment]
@toonarmycaptain Thanks for reporting. The issue - `relative-import` - was triggered due to `__init__.py` on root. Root directory name in this context is internal to CodeFactor (`_master`), so reported issue is not really a good candidate.

You should no longer see these type of issues.
