### ISSUE TITLE
Add TypeScript 3.7 support

### ISSUE THREAD

**Issue by nwtgck** [codefactor-io/codefactor#10]
Hi developers,

Thank you very much for the wonderful project! Currently, CodeFactor doesn't seem to support TypeScript 3.7 features such as Optional chaining and Nullish coalescing.

Here are CodeFactor's issues related to the features.
<https://www.codefactor.io/repository/github/nwtgck/piping-server/commit/5617fe76ebec4ac9337ca8690156ce7bfa359fa2>

Here is a PR auto-generated by CodeFactor.
<https://github.com/nwtgck/piping-server/pull/221/files>
The code change is not proper syntax in TypeScript 3.7.

### Example: Optional chaining
![image](https://user-images.githubusercontent.com/10933561/68306136-4c439200-00ec-11ea-9424-cbf0ac8d90d3.png)

### Example: Nullish coalescing
![image](https://user-images.githubusercontent.com/10933561/68306092-38982b80-00ec-11ea-9eb8-5d9f34612181.png)

**Comment by cordis-dev** [comment]
@nwtgck thanks for reporting, TypeScript is now updated to `3.7.2`.
