### ISSUE TITLE
Support for setting ignored paths in config file

### ISSUE THREAD

**Issue by zgoda** [codefactor-io/codefactor#18]
Now this requires going to project management page on codefactor.io and filling up the form. It would be great if this could be automated with kind of config file.

**Comment by cordis-dev** [comment]
@zgoda sorry for the delay. You can already do so via tool configuration files, depending on the language. E.g. Python's Pylint configuration has `ignore-patterns` key for this - https://github.com/codefactor-io/default-configs/blob/master/.pylintrc#L16.

To enable it though, you have to commit such file into your branch under certain name. More details: https://support.codefactor.io/i24-analysis-tools-open-source

**Comment by zgoda** [comment]
Will the patterns defined in pylint config be valid for duplication checker?

**Comment by cordis-dev** [comment]
No, there's a separate config for Duplication Checker. E.g. https://github.com/codefactor-io/default-configs/blob/master/.cfduplication.yml

Also, if the files you want to ignore are part of a larger pattern, we can exclude it by default.
