### ISSUE TITLE
Support custom/no file endings

### ISSUE THREAD

**Issue by MichaIng** [codefactor-io/codefactor#2]
We have a pure bash script project, but the main scripts have no file ending. Those are not checked by CodeFactor and I didn't find any way to add custom file endings for certain languages at all.

Would be great if there was a possibility to do the above. In case of shell scripts, the shebang could be used to identify the language/shell.

**Comment by cordis-dev** [comment]
Thanks for reporting and sorry for the delayed response.

Unfortunately this feature would be in conflict with our usage of [git sparse checkout](https://git-scm.com/docs/git-read-tree#_sparse_checkout) which allows us to reduce repo disk usage and support more repos at the same time. 

A similar trade-off would also be for supporting custom file endings. But if you could provide additional/common bash script file endings we would most likely include them as default.

**Comment by MichaIng** [comment]
@cordis-dev 
Yeah I understand that cloning the whole repo by default is no proper solution. I guess checking e.g. for a shebang to identify certain script types is as well nothing to achieve trivially, as still all files need to be read.

> A similar trade-off would also be for supporting custom file endings. But if you could provide additional/common bash script file endings we would most likely include them as default.

The problem is that in our project we use the shell/bash scripts as programs executable like any other binary from command line as alias respectively from `$PATH`. It would be simply not beautiful if it was required to start a program like `# program_name.sh`. Also it is very common on UNIX, a large share of the binaries inside `$PATH` locations are actually shell scripts and don't have any file endings.

Perhaps it would be considerable if one could add specific files from the repo handled as specific language type. This allows full flexibility while to user needs to do manual steps for each file that does not fit the default file ending rules. Not sure if the Git client provides the feature to achieve this in a clean and efficient way.

**Comment by kaskas** [comment]
@MichaIng
thanks for this feature request!

> The problem is that in our project we use the shell/bash scripts as programs executable like any other binary from command line as alias respectively from $PATH. It would be simply not beautiful if it was required to start a program like # program_name.sh. Also it is very common on UNIX, a large share of the binaries inside $PATH locations are actually shell scripts and don't have any file endings.

We understand your choice to NOT use file extensions for your scripts. Google's Shell Style Guide also "strongly prefers" not to use extensions for executables https://google.github.io/styleguide/shell.xml#File_Extensions. 

> Perhaps it would be considerable if one could add specific files from the repo handled as specific language type. This allows full flexibility while to user needs to do manual steps for each file that does not fit the default file ending rules. Not sure if the Git client provides the feature to achieve this in a clean and efficient way.

CodeFactor currently uses file extensions to map files to the respective languages for automated code analysis. Per your suggestion, we have introduced an Epic to CodeFactor's road-map that would support your use-case. There are significant considerations necessary to maintain CodeFactor's UX as frictionless as possible for our user base. We will prioritize implementation based on further needs of our community.

p.s. We love the https://github.com/MichaIng/DietPi project that you are curating!

**Comment by MichaIng** [comment]
@kaskas 
Many thanks by the way for your understanding and considering this feature request. I stay tuned.

**Comment by grm34** [comment]
Same here, have to create a specific branch and rename all project files to get it work.

**Comment by cordis-dev** [comment]
Deployed initial implementation for detecting Bash language files based on first line:
```
#!/bin/sh
#!/usr/bin/env sh
#!/bin/bash
#!/usr/bin/env bash
```

**Comment by grm34** [comment]
@cordis-dev thanks a lot, very appreciate 🖤

**Comment by MichaIng** [comment]
@cordis-dev 
Awesome, I'll re-enable CodeFactor on our project and see how it goes. Many thanks!
