### ISSUE TITLE
Problems with custom ESLint config parsing

### ISSUE THREAD

**Issue by vasilii-kovalev** [codefactor-io/codefactor#21]
Hello!

When a custom ESLint config is detected, the analyser throws the following warnings:
![image](https://user-images.githubusercontent.com/10310491/89719465-4bb88e80-d9d1-11ea-92ea-1e5198b1657b.png)

> client\.eslintrc - not supported dependencies: airbnb-typescript.
> client\src\wdyr.js:1 - Parsing error: 'import' and 'export' may appear only with 'sourceType: module'.

[The ESLint config](https://github.com/vasilii-kovalev/games_world/blob/master/client/.eslintrc).

Then I've updated ESlint config, pointing `"sourceType": "module"` in `parserOptions` as described [here](https://github.com/AtomLinter/linter-eslint/issues/462#issuecomment-190768439), but I still can see the error about that.

1. Where can I find the actual list of supported plugins?
2. If a plugin is not supported, its rules are just ignored or the linting fails silently?
3. Is it possible to support this plugin?
4. It would be great to have a link to the ESLint config that the analyser is using to check what version of ESLint (actually, any configs like Stylelint, TSLint, etc.) it uses. At least for custom configs.

Thanks in advance.

**Comment by cordis-dev** [comment]
@vasilii-kovalev Thanks for the feedback. `airbnb-typescript` config is now supported and your repo should no longer report related issue. 

By default, if `ESLint` fails using custom config it then analyses code using our default config which can be found at https://github.com/codefactor-io/default-configs.

Please visit https://support.codefactor.io/i24-analysis-tools-open-source to see OSS tool versions, supported plugins and default configurations.

**Comment by vasilii-kovalev** [comment]
@cordis-dev, thank you very much for the clarification and links! Now I can see that everything works fine, so closing the issue.
