### ISSUE TITLE
Codefactor reports error where there isn't one.

### ISSUE THREAD

**Issue by thsbrown** [codefactor-io/codefactor#23]
Codefactor is stating that I have missing documentation header (C#). Upon looking at the offending code I do in fact have a documentation header. Also when I try to trace down the issue on the code factor side it says there are no issues. I'm wondering what could be happening here 🤔 ?

![image](https://user-images.githubusercontent.com/2967721/95271763-900ab400-07f3-11eb-8c85-b03576c6b377.png)
![Snag_208016ee](https://user-images.githubusercontent.com/2967721/95271717-6f425e80-07f3-11eb-9a2c-00ec6d7aaea5.png)

Lastly even pressing the re-run button on github under checks doesn't seem to do anything.
![image](https://user-images.githubusercontent.com/2967721/95271887-e7108900-07f3-11eb-8fa8-7206d621597a.png)

Thanks for any help in advance!

**Comment by thsbrown** [comment]
It seems I may have figured out what was going on here. I ignored the issue codefactor was reporting (I think) on the codefactor side of things. However codefactor still seems to still report it on subsequent pushes.
![20495577-FFAB-4058-82FC-A2D0EF445B2E](https://user-images.githubusercontent.com/2967721/95272449-2ab7c280-07f5-11eb-91ac-d3c5ee224246.GIF)

**Comment by cordis-dev** [comment]
@thsbrown thanks for reporting. Regarding StyleCop false positive, could you (re)open a PR with suspected code for your repo in order for us reproduce the issue? CF does not inspect closed PRs by design.

Regarding ignored issues on CF side, it's could be a case of ignoring a single issue while you intended to ignore a whole pattern. More details: https://support.codefactor.io/i18-ignoring-issues-and-patterns

**Comment by thsbrown** [comment]
Unfortunately it would be a bit tough for me to re(open) a pr with the suspected code. I will however alert you if the issue crops up in the future!

I don't believe it was the case of ignoring a pattern vs the issue though as I remember reading over the result of each and specifically choosing the ignore single issue bit.

Thanks so much for the follow up 👍 .
