### ISSUE TITLE
Are ESLint custom configs supported?

### ISSUE THREAD

**Issue by tomcastro** [codefactor-io/codefactor#24]
Hi everyone!

We are trying out Codefactor for our organization and it works great so far.

Our only problem comes from having a custom ESLint configurations:

![image](https://user-images.githubusercontent.com/9694556/100004364-298f2480-2da6-11eb-91da-c5e14fc816da.png)

Our `.eslintrc.json` file:

```json
{
  "parser": "@typescript-eslint/parser",
  "extends": [
    "rokket-labs",
    "rokket-labs/react",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint"
  ],
  "settings": {
    "react": {
      "version": "detect"
    }
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "plugins": ["@typescript-eslint", "react"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "rules": {
    "react/prop-types": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": ["error"]
  },
  "overrides": [
    {
      "files": ["*.js"],
      "rules": {
        "@typescript-eslint/no-var-requires": "off"
      }
    }
  ]
}
```
The error reads out `not supported dependencies: rokket-labs`. Here's our [custom config](https://github.com/rokket-labs/eslint-config-rokket-labs).

Is this kind of configuration supported? I'm pretty sure we're not using any plugins outside of the ones specified [here](https://support.codefactor.io/i24-analysis-tools-open-source).

**Comment by cordis-dev** [comment]
@tomcastro thanks for reaching out. Yes, such configuration are supported. You should now see proper results for your repo.
