### ISSUE TITLE
Upgrade StyleCopAnalyzers to v1.2.0-beta.261

### ISSUE THREAD

**Issue by xtqqczze** [codefactor-io/codefactor#26]
In PowerShell/PowerShell#14301 we saw [spurious SA100 rule violations](https://www.codefactor.io/repository/github/powershell/powershell/commit/e0cda04d86297df8a07cd85ca73387f7bf185ceb) because the version of StyleCopAnalyzers in use by codefactor-io does not recognise C# 9.0 target-typed new expressions:

```
 The spacing around the keyword 'new' is invalid. lines of code = 1
Found in src\Microsoft.PowerShell.CoreCLR.Eventing\DotNetCode\Eventing\EventProviderTraceListener.cs:281
281
            StringBuilder failMessage = new(message);
```

The StyleCopAnalyzers issue was resolved in DotNetAnalyzers/StyleCopAnalyzers#3187 and was released in [v1.2.0-beta.261](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.261).

**Comment by iSazonov** [comment]
Since we are migrating all PowerShell code base to the new pattern _this would be nice to have._

**Comment by kaskas** [comment]
@iSazonov - automated #CodeQuality analysis for C# 9.0 is now available at CodeFactor.io. Enjoy!
