### ISSUE TITLE
Unfixed StyleCop issues shown as fixed

### ISSUE THREAD

**Issue by xtqqczze** [codefactor-io/codefactor#27]
In PowerShell/PowerShell#13396 we saw codefactor-io report [3542 fixed issues](https://www.codefactor.io/repository/github/powershell/powershell/commit-fixed/0d1ea73e599021c9ead87542646f7975bc04e5b9), that were not changed in the PR and in actual fact are unresolved in the `master` branch. We've been seeing many issues like this in the last month or so, but this is the most extreme case by far.

The cause of this issue might be that the project recently started using C# 9.0 features, like new `and`, `or`, and `not` keywords for pattern matching and target-typed new expressions and codefactor-io does not yet support C# 9.0, or is using old version of StyleCopAnalyzers.

See also: #26.

**Comment by kaskas** [comment]
@xtqqczze we have prioritized this ticket and it is currently Work-In-Progress. Some updates have already been pushed to production so you should already see improved analysis results for C# 8.0 and 9.0. The full scope will be rolled out by the end of January 2021.

**Comment by kaskas** [comment]
@xtqqczze Automated #CodeQuality analysis for C# 9.0 is now available at http://CodeFactor.io. Enjoy!
