### ISSUE TITLE
ESLint error using custom ESLint RC file

### ISSUE THREAD

**Issue by Puddinglord** [codefactor-io/codefactor#31]
![Screen Shot 2021-02-20 at 10 14 14 AM](https://user-images.githubusercontent.com/4474799/108600314-88901580-7364-11eb-8e4a-bb867172fc14.png)

I can't find anything that directly references jest in my eslintrc file. I also use jest for my testing suite so I can't remove it. How can I go about making the ESLint run not fail on CodeFactor so I can have auto-fixes again?

**Comment by cordis-dev** [comment]
Hi @Puddinglord, thanks for reporting. The repo you have at CodeFactor now looks to be configured Ok. 

If it's another repo we'd like to know it's name or content of the configuration file. If it's private please write to https://support.codefactor.io/add-ticket.

**Comment by Puddinglord** [comment]
Indeed, I found the offending line. Thanks for getting back to me!
