### ISSUE TITLE
Invalid custom config. Error

### ISSUE THREAD

**Issue by konkasidiaris** [codefactor-io/codefactor#32]
Hello,
today we set up our github repo with your service. In tools section under eslint there is this error "Invalid custom config."

I fooled around a little bit, changed some variables and fixed some too but the error still remains. Locally the eslint seems to work correctly. Can you please take a look at the .eslintrc and pinpoint what I am doing wrong?

```
{
  "env": {
    "es6": true,
    "node": true,
    "jest": true
  },
  "extends": ["airbnb-base", "plugin:prettier/recommended", "plugin:jest/recommended"],
  "plugins": ["jest", "prettier"],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly"
  },
  "parserOptions": {
    "ecmaVersion": 12,
    "sourceType": "module"
  },
  "rules": {
    "no-underscore-dangle": ["error", { "allow": ["_id"] }],
    "comma-dangle": ["warn", "never"],
    "prefer-arrow-callback": ["error"],
    "prefer-const": ["error"],
    "prefer-destructuring": ["warn", { "array": false, "object": false }],
    "space-before-function-paren": ["error", { "anonymous": "never", "named": "never", "asyncArrow": "always" }]
  }
}
```

Edit:
our dependencies
 "eslint": "7.20.0",
 "eslint-config-airbnb-base": "14.2.1",
 "eslint-config-prettier": "6.12.0",
 "eslint-plugin-import": "2.22.1",
 "eslint-plugin-jest": "24.1.0",
 "eslint-plugin-prettier": "3.1.4"

**Comment by cordis-dev** [comment]
@konkasidiaris thanks for reporting. It was an internal issue on our side - your repo should now report issues based on your custom config.

**Comment by konkasidiaris** [comment]
You are awesome, everything seems to work fine! Keep up the good work!!!
