### ISSUE TITLE
C# switch formatting bug

### ISSUE THREAD

**Issue by X9VoiD** [codefactor-io/codefactor#33]
CodeFactor is erroneously marking the semi-colon as an extra when it is required for this syntax.

CodeFactor:
![image](https://user-images.githubusercontent.com/10338031/111616436-d5102900-881c-11eb-9461-88f960893f59.png)

[EvdevVirtualTablet.cs#L91](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/31417a1b7627e18bb199f9f7a22a4be4ecaf4971/OpenTabletDriver.Desktop/Interop/Input/Absolute/EvdevVirtualTablet.cs#L91):
![image](https://user-images.githubusercontent.com/10338031/111616230-9c704f80-881c-11eb-8a56-5e93037556d4.png)

VS Code:
![image](https://user-images.githubusercontent.com/10338031/111616600-0d176c00-881d-11eb-99cf-433c210277e6.png)

**Comment by cordis-dev** [comment]
@X9VoiD thanks for a detailed report. We've updated our StyleCop integration - you should no longer see this false positive.
