### ISSUE TITLE
Android Tools configuration - custom checkstyle.xml

### ISSUE THREAD

**Issue by Koen-Kraak** [codefactor-io/codefactor#35]
Dear reader,

I've tried to setup a **custom checkstyle.xml** that should be used during pull request.

The documentation states: _"If engine is not provided with custom configuration it will use default rule-set. We reserve the right to disable selected rules without notice if necessary."_

Also when looking at the issues in a branch and expanding it, it mentions:
_"Have your own checkstyle rules? No problem, simply add checkstyle.xml file to the root of this branch."_

I've tried placing the checkstyle.xml in various folders but without success. It appears that the default config is still used.

Also when looking at the settings page, it appears to be described that the default one is used, but it does not provides any options to change it:
![image](https://user-images.githubusercontent.com/81751114/114674982-10acee80-9d08-11eb-916a-7588edb28629.png)

Could you please provide information about the steps needed to override the default configuration of the checkstyle.xml with my own custom checkstyle.xml?

Thanks in advance!

**Comment by cordis-dev** [comment]
@Koen-Kraak Hi, could you post the URL for the repo you're having issue with?

**Comment by cordis-dev** [comment]
@Koen-Kraak Hi, please check https://github.com/cordis-dev/cf-checkstyle-test for custom `checkstyle.xml` example.

**Comment by Koen-Kraak** [comment]
> @Koen-Kraak Hi, please check https://github.com/cordis-dev/cf-checkstyle-test for custom `checkstyle.xml` example.

Thanks for your reply,

When I placed the `checkstyle.xml` in the root folder op the repository, it still didn't apply that `checkstyle.xml` but instead it just used the default.

I verified this by making a pull request to be merged in the branch which has the `checkstyle.xml` in the root folder and in that pull request I intentionally added a // TODO: comment.
As can be seen in the [default config](https://github.com/codefactor-io/default-configs/blob/master/checkstyle.xml) the TodoComment is a violation that results in the message _"Resolve unexpected comment."_
![image](https://user-images.githubusercontent.com/81751114/114834842-3f42cc00-9dd1-11eb-86f1-52c538d7d078.png)

In my custom checkstyle there is a different error message, which was not shown in the pull request. Also other violations from my pull request weren't recognized as they are not in the default config.

Could you please validate that the custom checkstyle from https://github.com/cordis-dev/cf-checkstyle-test is respected by the codefactor review when pull request are made to that master branch?

Thanks in advance!

**Comment by cordis-dev** [comment]
@Koen-Kraak thanks for the details. The config resolution is working. The problem here is that we need more details regarding your repo to resolve this issue but it can't be addressed here due its private nature.

Could you post directly https://www.codefactor.io/contact and provide branch/PR URLs that are not working as expected?
