### ISSUE TITLE
Possible false positive for Complex Code issue

### ISSUE THREAD

**Issue by martinussuherman** [codefactor-io/codefactor#36]
Dear codefactor,

I think I might found a false positive, that codefactor sees this class: https://github.com/martinussuherman/PsefApiOData/blob/master/Models/ViewModels/OssFullInfo.cs as complex code. Here is the issue: https://github.com/martinussuherman/PsefApiOData/issues/3. I believe this should not be seen as complex, since this is just a POCO class, or I might be missing something? Any help is appreciated.

Regards,

Martinus

**Comment by cordis-dev** [comment]
@martinussuherman thanks for reporting. It was a false positive - you should now see it excluded from your repo issues.

**Comment by martinussuherman** [comment]
Thank you for the help @cordis-dev. Closing this issue now.

Regards,

Martinus
