### ISSUE TITLE
CodeFactor VSCode extension

### ISSUE THREAD

**Issue by Milo123459** [codefactor-io/codefactor#40]
I know one exists, but it could be expanded on:
An extension to get the issues you have to fix, and once you fix it, it makes a request to the API seeing if you fixed it, if you did, it'll remove the error from VSCode. By default all issues are noted as warnings if its a warning and a error if its an error

**Comment by cordis-dev** [comment]
@Milo123459 thank you for the feedback, we are looking into expanding functionality if this plugin.
