### ISSUE TITLE
Trouble with custom bandit config

### ISSUE THREAD

**Issue by djhoese** [codefactor-io/codefactor#43]
I have a branch with a custom bandit config named `.bandit` in the root of the repository. Its contents are:

```ini
[bandit]
skips: B506
exclude: satpy/tests
```

Which are described [here](https://github.com/PyCQA/bandit#per-project-command-line-args). However, CodeFactor seems to not recognize/use the `skips` parameter as I still get failures for B506: https://www.codefactor.io/repository/github/pytroll/satpy/pull/1901. This configuration seems to work when using bandit locally.

Any ideas what I'm doing wrong? Is this a bug in bandit? In CodeFactor?

**Comment by cordis-dev** [comment]
@djhoese thanks for reporting. It was an issue on CodeFactor. The PR for your repo should no longer report ignored issue.

**Comment by djhoese** [comment]
Thanks @cordis-dev. The B506 does seem to be skipped now, but now the `exclude` directory seems to be ignored as I'm getting issues identified with using `assert` in my satpy/tests directory.

**Comment by cordis-dev** [comment]
The path for `exclude:` was not resolving as expected. Thanks again. The PR should now exclude ignored paths.

**Comment by djhoese** [comment]
Looks good now. Thank you!
