### ISSUE TITLE
Custom bandit config being ignored again

### ISSUE THREAD

**Issue by djhoese** [codefactor-io/codefactor#46]
This is related to #43. A new PR (https://github.com/pytroll/satpy/pull/2032) of mine seems to be complaining about something I expected to be ignored based on the custom bandit config I have:

```
[bandit]
skips: B506
exclude: satpy/tests
```

Are sub-directories not part of the exclude? Here's the error/job:

```
 codefactor-io codefactor-io / CodeFactor

satpy/tests/writer_tests/test_awips_tiled.py#L373

Use of assert detected. The enclosed code will be removed when compiling to optimised byte code. (B101)
```

https://github.com/pytroll/satpy/pull/2032/checks?check_run_id=5279154018

**Comment by cordis-dev** [comment]
@djhoese thanks for reporting. It was a regression due to Bandit upgrade. The ignored path should now be respected.

**Comment by djhoese** [comment]
Looks good! Thanks!
