### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by matthiasn** [codefactor-io/codefactor#48]
Hi, I recently started seeing hundreds of false positives, for [example](https://github.com/matthiasn/lotti/runs/7145723185):

![image](https://user-images.githubusercontent.com/1390808/176883568-41a040f4-8648-496b-8a3e-6ad171804a3b.png)

**Comment by cordis-dev** [comment]
@matthiasn thanks for reporting. We've resolved related flutter dependencies issue which should address the false positives for `matthiasn/lotti` repo.

**Comment by matthiasn** [comment]
@cordis-dev thanks, I can confirm that it's working fine again.
