### ISSUE TITLE
Possible CWE-78 False Positive

### ISSUE THREAD

**Issue by XPhyro** [codefactor-io/codefactor#49]
You can see the issue on https://www.codefactor.io/repository/github/xphyro/scripts/issues or a screenshot of it below.

![2022-08-05_20-27](https://user-images.githubusercontent.com/10392678/183129708-45d8cc98-6e9c-4868-b066-92a2f8a6ad97.png)

I'm specifically passing `path` as the last argument because that is what it is, a path to pass to the `file` command. Embedded spaces are not an issue here as I'm using `execlp`, not other functions like `system`. It's also worth noting that `clang-tidy` version 14.0.6 reports no issues here.

The only possible security issue I can see is the fact that I use a `p` variant of `exec`, and an attacker could include a malicious command named `file` somewhere in PATH with higher priority. Although even this is a stretch as a user (or root) is unlikely to include a directory whose write bit is set for group/everyone in their PATH. Lastly, CWE-78 is issued by CodeFactor even when using a non-`p` variant such as `execl`, and the explanation does not seem relevant at all.

I think this is a false positive. If not, please enlighten me on what the issue here is.

**Comment by cordis-dev** [comment]
@XPhyro thanks for reporting. CWE-78 check comes from Flawfinder tool - https://github.com/david-a-wheeler/flawfinder/blob/master/flawfinder.py#L1386 i.e. currently it does not have any additional checks like arguments.

We will upgrade the tool as soon as it's updated to resolve this issue. Alternatively, you can also disable issues (by one or by category) via CodeFactor - https://support.codefactor.io/i18-ignoring-issues-and-patterns.

**Comment by Madoox07** [comment]
> You can see the issue on https://www.codefactor.io/repository/github/xphyro/scripts/issues or a screenshot of it below.
> 
> ![2022-08-05_20-27](https://user-images.githubusercontent.com/10392678/183129708-45d8cc98-6e9c-4868-b066-92a2f8a6ad97.png)
> 
> I'm specifically passing `path` as the last argument because that is what it is, a path to pass to the `file` command. Embedded spaces are not an issue here as I'm using `execlp`, not other functions like `system`. It's also worth noting that `clang-tidy` version 14.0.6 reports no issues here.
> 
> The only possible security issue I can see is the fact that I use a `p` variant of `exec`, and an attacker could include a malicious command named `file` somewhere in PATH with higher priority. Although even this is a stretch as a user (or root) is unlikely to include a directory whose write bit is set for group/everyone in their PATH. Lastly, CWE-78 is issued by CodeFactor even when using a non-`p` variant such as `execl`, and the explanation does not seem relevant at all.
> 
> I think this is a false positive. If not, please enlighten me on what the issue here is.

<tuit> 5493< marsh #auxinrojasvalverde

**Comment by michpolicht** [comment]
Made totally flawed check in my case reporting this as OS injection:

```
QString language = QLocale::system().name();
```
All this line does is getting the system locale name using static `QLocale::system()` method... It thinks I execute something like `system(<very dangerous command>)`, where `<very dangerous command>` = `).name(`.

**Comment by cordis-dev** [comment]
@michpolicht thanks for reporting. We've now updated Flawfinder to exclude this kind of false positive. Let me know if this issue is still present for your repo.
