### ISSUE TITLE
Typo in python 'Lambda may not be necessary' readup 

### ISSUE THREAD

**Issue by desbonnm** [codefactor-io/codefactor#5]
The readup for the python 'Lambda may not be necessary' alert looks to contain a typo.

I think
```
results = " ".join(rdd.map(save_and_show.collect())
```
should be
```
results = " ".join(rdd.map(save_and_show).collect())
```

**Comment by cordis-dev** [comment]
@desbonnm Thanks for reporting. The readup should now be updated.
