### ISSUE TITLE
`not supported dependencies: plugin:functional/all`

### ISSUE THREAD

**Issue by scarf005** [codefactor-io/codefactor#53]
![image](https://user-images.githubusercontent.com/54838975/205845730-2c3a0b3f-70e6-44c9-a844-e3f9d733bd49.png)

`.eslintrc.yml - not supported dependencies: plugin:functional/all.`

1. can it run without unspported dependencies?
2. would it possible for codefactor to be able to install custom eslint plugins specified in package.json?

<details>
	<summary>eslintrc.yml</summary>
	<pre>
	env:
	  browser: true
	  es2021: true
	
	extends:
	  - eslint:recommended
	  - plugin:react/recommended
	  - plugin:react/jsx-runtime
	  - plugin:@typescript-eslint/recommended
	  - plugin:functional/all
	
	parser: "@typescript-eslint/parser"
	parserOptions:
	  ecmaVersion: latest
	  sourceType: module
	  ecmaFeatures:
	    jsx: true
	
	settings:
	  react:
	    version: detect # https:stackoverflow.com/a/71436488
	
	plugins:
	  - react
	  - "@typescript-eslint"
	  - functional
	  - unused-imports
	
	rules:
	  curly:
	    - error
	    - all
	
	  # prettier
	  indent: off
	  linebreak-style: off
	  quotes: off
	  semi: off
	  max-lines: off
	
	  # 함수형 프로그래밍
	  functional/prefer-readonly-type: off
	  functional/immutable-data: warn
	  functional/no-expression-statement:
	    - warn
	    - ignoreVoid: true
	  functional/functional-parameters: off
	  functional/no-conditional-statement:
	    - warn
	    - allowReturningBranches: true
	
	  unused-imports/no-unused-imports: error
	
	overrides:
	  # 컴포넌트 타입은 리터럴과 함수를 모두 받아야 함
	  - files: ["**/*.tsx", "**/*.test.ts*"]
	    rules:
	      functional/no-mixed-type: off
	
	  # 테스트 파일에서 vitest 관련 함수 허용
	  - files: ["**/*.test.ts*"]
	    rules:
	      functional/no-expression-statement:
	        - warn
	        - ignoreVoid: true
	          ignorePattern: [test, expect, to.*]
	
	  # 스토리 파일에서 OBJ.args = { KEY: VALUE } 대입 허용
	  - files: ["**/*.stories.ts*"]
	    rules:
	      functional/no-expression-statement:
	        - warn
	        - ignoreVoid: true
	          ignorePattern: [args]
	
	      functional/immutable-data:
	        - warn
	        - ignoreAccessorPattern: "**.args"
	</pre>
</details>

**Comment by cordis-dev** [comment]
@scarf005 thanks for reporting. `functional` plugin for ESLint is now supported and your repo should generate full list of configured issues.
