### ISSUE TITLE
Outdated cpplint.py

### ISSUE THREAD

**Issue by Jhuighuy** [codefactor-io/codefactor#54]
Hi!

Looks like the `cpplint.py` is outdated and cannot handle the C++17 (and more recent) code.

For example, consider this issue:

https://www.codefactor.io/repository/github/jhuighuy/stormruler/source/main/source/Storm/Bittern/MatrixMath.hpp#L53

Cpplint complains that `<tuple>` header is not included, although it is clearly included on the top of the file. 

Maybe it whould be a considerable option to switch to this fork:
https://github.com/cpplint/cpplint 
It is much freshier and understands C++ better.
When I run the forked version of `cpplint` locally, this issue is gone (and also many others caused by outdated `cpplint`).

**Comment by cordis-dev** [comment]
@Jhuighuy thanks for reporting. CodeFactor now uses `cpplint/cpplint` fork and your repo was re-inspected. Let me know if you find any other issues.
