### ISSUE TITLE
False positive "Complex Method"

### ISSUE THREAD

**Issue by Elringus** [codefactor-io/codefactor#55]
Hi, I believe this is a false-positive: https://www.codefactor.io/repository/github/naninovel/language/source/main/backend/Naninovel.Language/Token/TokenHandler.cs#L23 I'm aware it's possible to ignore specific issues, but just wanted to let you know in case the analysis can be improved somehow.

**Comment by cordis-dev** [comment]
@Elringus thanks for reporting. It is a false-positive. We'll update this ticket and re-inspect your repo once this issue is resolved.

**Comment by cordis-dev** [comment]
@Elringus Hey, your repo should now exclude reported false positive. Let me know if you still have an issue!
