### ISSUE TITLE
Add Rust support

### ISSUE THREAD

**Issue by notquiteamonad** [codefactor-io/codefactor#6]

**Comment by kaskas** [comment]
Hi @samueldple - thank you for this feature request. Rust is within 20 top growing languages on Github this year according to https://octoverse.github.com/ and we are looking  into adding Rust to the ever-growing bucket of supported languages at CodeFactor. Stay tuned!

**Comment by ismail-ra** [comment]
53228

**Comment by ismail-ra** [comment]
#10

**Comment by Milo123459** [comment]
Are there any ETAS?

**Comment by kaskas** [comment]
Hi @Milo123459, due to the receding popularity of the language, but more importantly due to slow rust-clippy linter performance and significant difficulty of customizations, we have deprioritized Rust analysis support at this time. No ETA.

**Comment by Milo123459** [comment]
Clippy seems to run ridiculously fast for me. Would you mind sharing what makes you think it's slow?
