### ISSUE TITLE
C# 12.0 support

### ISSUE THREAD

**Issue by DarkStoorM** [codefactor-io/codefactor#60]
In the Settings -> Tools I'm getting parse errors for StyleCop analyzer with the following line:

```cs
public class CommandHandler(string message, string senderId, string senderName, string hexColor, bool isPrivileged)
{
[...]
```

I assume it doesn't support C# 12.0 features yet, e.g. [Primary Constructors](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/primary-constructors) like above and on collection expressions. This is also the reason why I stopped getting rule violation and complexity reports in most of the files.

![1](https://github.com/codefactor-io/codefactor/assets/7021295/0a7f3d1c-bd7e-45c4-8060-dad7d48af29c)
![2](https://github.com/codefactor-io/codefactor/assets/7021295/35ce6f6e-a1af-4903-85cb-f25f3e1341b6)
![3](https://github.com/codefactor-io/codefactor/assets/7021295/26eebc01-a888-4aeb-a0b0-587470e98ce8)

**Comment by cordis-dev** [comment]
@DarkStoorM thanks for reporting, we'll look into this.

**Comment by cordis-dev** [comment]
C# 12.0 features like primary constructors and collection expressions should now be supported for StyleCop linter.
