### ISSUE TITLE
See linter warnings as warnings on CodeFactor (ESLint)

### ISSUE THREAD

**Issue by Jxlle** [codefactor-io/codefactor#62]
Currently, it seems that linter rules that serve as a warning, and not an error, are also reported as an issue in CodeFactor. When using CodeFactor as a PR check, it blocks the PR, even if all errors are resolved but there are still warnings.

Is there a way to classify linter warnings as non-blocking issues on PR's?

**Comment by cordis-dev** [comment]
@Jxlle thanks for reporting. Could you give an example PR where this is the case? CodeFactor has several issue severities, I want to make sure that warnings are mapped properly.

**Comment by Jxlle** [comment]
@cordis-dev We use Cypress for E2E testing and also use their ESLint plugin to check for errors/warnings. We enabled two Cypress rules:
- "cypress/no-unnecessary-waiting": "warn"
- "cypress/unsafe-to-chain-command": "warn"

but these warnings are reported as 'issues' when CodeFactor checks the PR, making the check fail. You can actually see the second rule turned off in our config in [this PR](https://github.com/codefactor-io/codefactor/issues/63) with the comment that CodeFactor makes the PR fail if these rules are violated (and thus generate warnings).

**Comment by cordis-dev** [comment]
@Jxlle  thanks for the feedback. We've added an option on repository `Settings` page to change behavior for Minor Issues (warnings) which is related to Pull Request Checks:

![image](https://github.com/codefactor-io/codefactor/assets/1436131/c5973ea8-4eda-4ecf-8f16-f68c2f7251e0)

If you toggle it to `On` it should no longer block PR checks if all reported issues are minor (warnings).

**Comment by Jxlle** [comment]
Hi @cordis-dev, I'll test this asap! (after https://github.com/codefactor-io/codefactor/issues/64 is also resolved)

**Comment by Jxlle** [comment]
@cordis-dev This update seems to work, thanks! 

**Note on user interface**: I'm not sure, but do the issues (warnings & errors) get separated in the dashboard at this time? Seemed to me that they all were classiefied as issues. Would be nice to have it display 'issues' and 'minor issues' as separate labels in a future update and filter between them. (maybe have minor issues in orange instead of red?)

**Comment by cordis-dev** [comment]
@Jxlle glad to help. 

Regarding UI for issues, we're considering adding a Severity filter to address this issue. Currently you can see issue severity as part of issue info at the header:

![image](https://github.com/codefactor-io/codefactor/assets/1436131/86259f8e-d0b9-4ee5-9b8b-368a5b66225c)
