### ISSUE TITLE
Wrong profile picture

### ISSUE THREAD

**Issue by Lenochxd** [codefactor-io/codefactor#66]
https://www.codefactor.io/repository/github/lenochxd/webdeck

On my project's codefactor page, my profile photo has been replaced by a contributor's pfp (https://github.com/NicoSinban)

I don't know if this has anything to do with it, but it happened on Nico Sinban's first commit (https://github.com/Lenochxd/WebDeck/commit/4f9ad725589680ce9351327a37e1afe62f281cc9), done from my computer using GitHub Desktop, in which he just changed the email address to commit from his account.

**Comment by cordis-dev** [comment]
@Lenochxd thanks for reporting, we're looking into this issue.

**Comment by cordis-dev** [comment]
@Lenochxd you should now see correct profile photos on your repo page.
