### ISSUE TITLE
Add Dart support

### ISSUE THREAD

**Issue by mpfaff** [codefactor-io/codefactor#7]
Are there any plans to add Dart support?

**Comment by kaskas** [comment]
Hi @PfaffDev  - thank you for this request. Dart is on our roadmap. Prioritization of new language rollout is based on demand. Looks like early 2020 at the moment. Stay tuned!

**Comment by kaskas** [comment]
Hey @pfaffdev - I'm happy to announce that CodeFactro.io now supports Dart. Ahead of schedule due to demand. We see significant ramp-up in Flutter usage. Enjoy it at https://codefactor.io
