### ISSUE TITLE
.eslintrc.js support

### ISSUE THREAD

**Issue by Hongbo-Miao** [codefactor-io/codefactor#8]
Please support .eslintrc.js, thanks!

![image](https://user-images.githubusercontent.com/3375461/63891969-4cf8d300-c99b-11e9-8ca8-02c1c0c4e9f5.png)

**Comment by kaskas** [comment]
Dear @Hongbo-Miao 

This is by design.

**We believe that allowing arbitrary code execution is inherently untrustworthy (irrespective of containerization or other layers).** 

We do support all other formats - see https://eslint.org/docs/user-guide/configuring#configuration-file-formats
