### ISSUE TITLE
.stylelintrc.js support

### ISSUE THREAD

**Issue by Hongbo-Miao** [codefactor-io/codefactor#9]
Please support .stylelintrc.js, thanks!

![image](https://user-images.githubusercontent.com/3375461/63892040-7c0f4480-c99b-11e9-804b-dd3fee3d70d6.png)

**Comment by kaskas** [comment]
Dear @Hongbo-Miao 

This is by design

**We believe that allowing arbitrary code execution is inherently untrustworthy (irrespective of containerization or other layers).** 

We do support all other formats - see https://eslint.org/docs/user-guide/configuring#configuration-file-formats
